- data/en/cfabort.json
- data/en/cfajaximport.json
- data/en/cfapplication.json
- data/en/cfcomponent.json
- data/en/cfinput.json
- data/en/cfquery.json
- data/en/cfselect.json
> Remove invalid characters and fix spacing of `SELECT`.

- data/en/dateadd.json
If you execute the example code it actually adds weekdays, not weeks to the date.  This corrects it.
> fix example code to use weeks not weekdays

- assets/style.css
- views/doc.cfm
The ACF, Lucee and OpenBD labels in the engine list now use colors
pulled from their respective websites to apply more obvious visual
connections to the engines themselves.
> Add engine-specific labels and colors

- assets/code-editor.css
- assets/code-editor.js
- trycf.cfm
With the change to load the trycf editor in a modal on demand there were some supporting assets that were not being loaded (bootstrap css/js, font-awesome), which caused the formatting issues and js errors.  
Also fixed a few editor issues with saving a gist and editor full-screen mode.
> Fixes formatting & js issues in trycf editor

- data/en/cfquery.json
This is an example of the script based tag-as-component syntax of making queries in CF9 and 10 prior to the introduction of queryExecute() in 11.
> Addition of script syntax for new Query() function for CF 9-10.

- data/en/writedump.json
I thought it valuable to show you can add the abort flag to the writeDump function as opposed to immediately following it with an abort command.
> Added abort flag to params list

- data/en/cfquery.json
Fixed example code for queryExecute() to use parameters correctly.
> Updates to cfquery docs

- views/doc.cfm
- views/layout.cfm
Adding the missing examples page to the "Other" menu and fixing a bug that was preventing reports from showing.
> Missing examples to menu and bug fix.

- data/en/esapiencode.json
Michael Offner (Lucee): EsapiEncode is deprecated now and encodeForHtml is not!
> EsapiEncode is deprecated

- assets/style.css
This will highlight the current typeahead result when using the arrow
keys to step through typeahead search results (matching the mouse hover
style).
> highlight current item when stepping through typeahead results

- data/en/cfmail.json
Added query (#225) and SMTP examples. Changed email addresses to example.com as
per IANA practice.
> cfmail query example

- Application.cfc
Markdown links `[text](url)` get screwed up because the autolink method
replaces links that are already links. This should fix it by only
replacing links that don't have `"` in front of them.
> Fix markdown links

- data/en/deserializejson.json
I agree with Adam
(http://blog.adamcameron.me/2016/01/coldfusion-how-not-to-document-function.html)
this makes the example more focused.
> deserializeJSON() replace escaped double quotes

- data/en/date-and-time-functions.json
- data/en/formatting-functions.json
Just adding dateTimeFormat to the date-and-time functions and the formatting functions.
> Adding dateTimeFormat to function listing pages.

- data/en/cflocation.json
I see that the full syntax for both is demonstrated in the code examples at the bottom, but the top examples implied to me (at first glance) that the tag version does not have the `statusCode` attribute.
> Just making the tag syntax equivalent to the script syntax.

- guides/en/closures.md
Link was pointing to "/ArrayFindAt" which doesn't exist. I suspect that was meant to be "/ArrayFindAll"
> Fix link to ArrayFindAll

- views/index.cfm
A couple of fixes for the homepage, so the contributors section looks
better on tablets (2 col) and phones (1 col).
> homepage: responsive fix for contributors section

- data/en/arraynew.json
From the Adobe documentation:
Unsynchronized arrays
The 2016 release of ColdFusion comes with support for unsynchronized arrays. Users can create
unsynchronized arrays by passing a special flag to arrayNew method. By default, the arrays are
synchronized for backward compatibility. Unsynchronized arrays are about 93% faster due to lock
avoidance. Please note that they are not thread safe. You should use them when you do not need thread
safety.
Sample code to create an unsynchronized array:
ar_obj = arrayNew(numeric dimension, boolean unsynchronized);
> Added param unsynchronized

- data/en/structmap.json
I couldn't find any docs on minimum version of Lucee for this function so I just guessed 4.5
> For #356, fix lucee compat warning for StructMap

- data/en/createodbcdate.json
- data/en/createodbcdatetime.json
- data/en/createodbctime.json
- data/en/dateadd.json
- data/en/dateconvert.json
- data/en/datediff.json
- data/en/dateformat.json
- data/en/datepart.json
- data/en/datetimeformat.json
- data/en/day.json
- data/en/dayofweek.json
- data/en/dayofyear.json
- data/en/daysinmonth.json
- data/en/daysinyear.json
- data/en/firstdayofmonth.json
- data/en/hour.json
- data/en/lsdateformat.json
- data/en/lstimeformat.json
- data/en/minute.json
- data/en/month.json
- data/en/quarter.json
- data/en/second.json
- data/en/timeformat.json
- data/en/week.json
- data/en/year.json
@pfreitag: Could you review this? I put information about when the member functions were added in the notes for the engines. I am not sure you want it there, but I wasn't sure if there was a better place to put it.
There are two places where I added additional notes:
- `datepart.json`: the syntax differs between CF and Lucee - I added that to the notes under the Lucee engine. 
- `datediff.json`: here it seems that CF and Lucee behave differently with how they diff the dates. I added a note about it to the Lucee engine, as well as an example that can be run that illustrates the difference.
CF2016 also has the `.setSecond()`, `.setMinute()`, etc. member functions, but since there are no corresponding BIFs I wasn't sure what to do with them.
Let me know if anything needs to be changed.
> Added date member functions

- data/en/cfschedule.json
They're somewhat wimpy little examples, but they'd sure be helpful next time!
I made sure to set `runnable` to `false` for both examples. I'm absolutely sure that `trycf.com` won't support any scheduling CFML.
> Added create and delete examples for cfschedule

- data/en/generatesecretkey.json
Added information for the keysize argument of this function - checked that it definitely exists for Lucee 4.5 and 5, using trycf.com as well as ACF. Although the coldfusion docs say that this was added for ACF8+ (can we add argument-specific version info to the engines section?).
> Missing keysize argument for generateSecretKey.

- data/en/cacheget.json
- data/en/cacheput.json
Expanded on the argument references to include Lucee arguments, denoting
differences
Added CF10+ to cachePut region argument
Added additional examples for script syntax (cacheput) and named caches
> Additional details and examples for cacheget and cacheput

- data/en/refindnocase.json
De-capitalized string param name to be consistent with other params.  Moved the default of "1" from string param to start param.
> Minor param corrections to ReFindNoCase

- data/en/refind.json
Also, Adobe's description on their help page doesn't mention that it starts from a specified position.  I added that information (which makes it consistent with ReFindNoCase
> Add description to ReFind

- data/en/fileupload.json
First, never upload directly to a web accessible directory. Second, always check the incoming file extension. Checking on mime type alone does not do it, this can be easily spoofed.
> Improvements in file upload example

- guides/en/security-authentication.md
- guides/en/security-session-management.md
Resolves an issue folks are running into using the code examples under
CommandBox, where the port is being included with CGI.HTTP_HOST,
preventing the cookie from being returned by the browser.
> Update code examples for CommandBox

- data/en/cfoutput.json
Because `cfloop(query="x" group="y")` is the cfscript version of `<cfoutput query="x" group="y">`.
> Add cfloop to "see also" section of cfoutput

- data/en/paragraphformat.json
The description on https://cfdocs.org/paragraphformat outputs the `<p>` in the example verbatim onto the page, which leads to an empty pair of parens.
I encoded the angle brackets.
> Encode brackets in <p> in paragraphFormat docs

- data/en/htmlcodeformat.json
I switched these out for entities, so that the block doesn't look like this:
> Add entities to description of the htmlCodeFormat function

- assets/style.css
I find reading the listing of functions when forced to uppercase hard to read. I've overwritten the Bootstrap CSS to removed the transformation.
> Overwrite forced uppercase of functions in listings

- data/en/cfoutput.json
This extends the descriptions of the `startrow` and `maxrows` attributes and adds and example related to them to make it clear how they are used.
> Clarified usage of 'startrow' and 'maxrows' attributes and added an example for their usage

- data/en/cftimer.json
I wasn't able to get these examples to run properly on the Adobe servers in the pop up runner so I set the runnable property to false to avoid confusion. Let me know if I'm missing something there.
Thanks!
> add tag and script examples for cftimer

- data/en/componentinfo.json
According to docs: http://docs.lucee.org/reference/functions/componentinfo.html
> [minor] Deprecated componentInfo()

- data/en/cachekeyexists.json
Added note to use CacheIdExists instead as this function is deprecated. This got lost in my previous update to this page.
> Added note to use cacheIdExists instead

- data/en/getfunctionkeywords.json
I happened to notice this `getfunctionkeywords()` function is missing a description. (To say the least.) I updated this with the description from the Lucee docs.
http://docs.lucee.org/reference/functions/getfunctionkeywords.html
> Added basic function description to getfunctionkeywords().

- data/en/cfheader.json
Calling cfheader(), the script-based version of this tag, is only available on CF11+. CF10 will trigger a 500 "Variable CFHEADER is undefined" error.
> Added compatibilty note for script version of tag

- data/en/ormevictqueries.json
Changed "quiries" to "queries".
https://cfdocs.org/ormevictqueries
> Fixed misspelling in OrmEvictQueries.json

- data/en/cfmailparam.json
Added Lucee support notice for tag param "filename" (since 5.1.0.17: https://luceeserver.atlassian.net/browse/LDEV-885)
> Added Lucee support notice for param "filename" in cfmailparam tag

- assets/style.css
Example: https://cfdocs.org/replacelist
padding is only applied to the first line
> Fix newlines in case of multiple function signatures

- views/doc.cfm
Example: https://cfdocs.org/lsparsedatetime
Related to: #793
> Fix syntax output which is multiline now

- CONTRIBUTING.md
Example: https://cfdocs.org/how-to-contribute
"LICENSE" links to https://cfdocs.org/LICENSE
> Cleanup and make proper links for accessing from cfdocs.org

- data/en/arrayeach.json
- Add engine labels instead of "{engine} only" string
- Simplified boolean parameter description
- Boolean parameter need no explicit values
- Correct param type of `maxThreads` must be numeric (defaults to a number)
- Cleanup code of example 1
- Remove unnecessary description of example 2
> Various changes in arrayEach()

- data/en/structfind.json
The `defaultValue` parameter is currently only supported by Lucee and their docs don't specify what's the default value for that parameter.
Not sure whether the note for its support should be at the parameter or at the engines. I've mentioned it in the description for the parameter itself, so it's obvious when looking at it.
> Added example to structFind() and optional 'defaultValue' parameter

- data/en/structappend.json
Added a practical example use of structAppend() by demonstrating how to construct a request context from the form and url scopes.
> Add example of creating request context

- data/en/decision-functions.json
Fixed typo from isSoapReqiest to isSoapRequest.  This was also resulting in a 404 when the link was clicked.
> Fix typo from isSoapReqiest to isSoapRequest

- data/en/getlocaleinfo.json
I've added the general description for the function, removed the incorrect `"discouraged"` item, fixed the name of the second parameter, explained the parameters in more detail, added a link to the Lucee documentation, added a third example showing how to change the output language, and improved the descriptions for the existing examples.
> Corrected and clarified description of getLocaleInfo() and added a third example

- data/en/structappend.json
> fix #904 | Example "Polyfill for ealier versions": putAll()

- data/en/cfdocumentitem.json
Basic script syntax examples for cfdocumentitem.
> Add cfdocumentitem examples for pagebreak and footer.

- data/en/evaluate.json
Updated the link to point to the new Adobe page which discourages `Evaluate()`.
> Correct broken link in Evaluate doc page. Fixes #927

- data/en/millisecond.json
Added descriptions to arguments from the Lucee documentation located here - https://docs.lucee.org/reference/functions/millisecond.html
> Added descriptions to arguments for millisecond

- data/en/esapidecode.json
Fix #943
According to deprecation of esapiEncode in https://github.com/foundeo/cfdocs/commit/86cb9c68686d3de74be69ada44e6bdf65446258c
> Marked as deprecated #Hacktoberfest

- data/en/duplicate.json
Fix #853
String doesn't make sense, because there is no real reference
Suggested by @jinglesthula
> Better example for duplicate() #Hacktoberfest

- data/en/getmetricdata.json
Fix #911
According to https://github.com/lucee/Lucee/blob/5.2.9.31/core/src/main/java/lucee/runtime/functions/system/GetMetricData.java#L32
> Add deprecation note to getMetricData #Hacktoberfest

- data/en/listtrim.json
Added descriptions to arguments from the Lucee documentation located here - https://docs.lucee.org/reference/functions/listtrim.html
And added deprecation note according to those docs and here https://github.com/lucee/Lucee/blob/5.2.9.31/core/src/main/java/lucee/runtime/functions/list/ListTrim.java#L36
> Added descriptions to arguments for listTrim and deprecated

- utilities/indexer.cfm
Puts tags/functions added in an update version into the list for the major release.
Will handle current versioning (2016.0.#) and past versioning (11.0.#).
> Add support for semantic version numers to listing indexes

- data/en/listfilter.json
listFilter example was copied from arrayFilter.  Changed to listFilter with a simple numbers list.  Also removed non-existent member function.
> Fixed listFilter example

- views/doc.cfm
and let them collapse/expand independently
Fix #864
> Expand the first five examples by default

- data/en/structeach.json
example for structEach was using arrayEach and caused an error when run.
> example for structEach was using arrayEach

- data/en/getnumericdate.json
Last one should have been `writeoutput(getNumericDate(date2)-getNumericDate(date1) & \" days\");` but one can use dateDiff() instead.
> Remove duplicate and wrong example

- guides/en/for.md
`currentrow` is a member of the query object, not the index.
> Fix invalid currentrow usage

- guides/en/security-encryption.md
Added Missing Parenthesis to the guide.  Not entirely sure why git thinks the last paragraph has changed.  Must be the line endings.
> Added Missing Parenthesis

- data/en/listappend.json
This doc is a bit confusing when you are new to CF because unlike every other CF append function (array, struct) it isn't atomic, even when the member syntax is used. I added this to the description and the code examples to highlight this. listPrepend's doc clearly shows the proper use. Which is how I figured out what was wrong in my own code.
> listAppend returns the concatenated list

- data/en/arrayreverse.json
Not quite sure how to document this, but raising a PR. 
ArrayReverse does not exist in ColdFusion but you can get the same result by using the array slice syntax `[::-1]` adding in ACF 2018. Have added an example  of doing it in ACF2018, but not sure how you'd normally handle this as it's an equivalent.
> ArrayReverse example using different syntax in ACF2018

- data/en/cfmailpart.json
Just some repeated characters. `type can be a valid MIME`
> Fix typo in cfmailpart

- data/en/entitynew.json
This is documented in Lucee: https://docs.lucee.org/reference/functions/entitynew.html and ACF: https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-e-g/entitynew.html.
If I wasn't so lazy, I'd add an example while I was at it. :)
> Add docs for `properties` parameter in entityNew

- data/en/encodefor.json
- data/en/encodeforcss.json
- data/en/encodefordn.json
- data/en/encodeforhtml.json
- data/en/encodeforhtmlattribute.json
- data/en/encodeforjavascript.json
- data/en/encodeforldap.json
- data/en/encodeforurl.json
- data/en/encodeforxml.json
- data/en/encodeforxmlattribute.json
- data/en/encodeforxpath.json
The decision to deprecate these `encodeForHTML()`, `encodeFor*()` functions has been reversed per Brad Wood and others more informed than I. :)
See https://groups.google.com/forum/#!topic/lucee/90xgx_wnVs4,
https://cfml.slack.com/messages/C06TA0A9W/convo/C06TA0A9W-1558749781.016600/
> Mark encodeFor* functions as *not* deprecated

- data/en/gettimezoneinfo.json
* Add description of `timezone` argument in Lucee
* Add `locale` argument with description
* Add example of using timezone and locale together
* Clean up the other example just a bit.
> Describe timezone and locale arguments for getTimeZoneInfo()

- data/en/cfqueryparam.json
As shown in https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-p-q/cfqueryparam.html, and as experienced by my upgrade from CF2016 to CF2018 this morning.
> Add default value for `scale` argument of cfqueryparam

- data/en/canonicalize.json
> Typo: "Adode" to "Adobe" in canonicalize() code examples

- data/en/writeoutput.json
Lucee 5.1.0.8+ supports the `encodeFor` attribute on `writeOutput()`. I'm not certain that tag `Lucee5.1.0.8+` will work, but here goes. :)
(If that tag doesn't work, should we update the engine regex or just note it as "Since Lucee 5.2+`?
https://docs.lucee.org/reference/functions/writeoutput.html
> Add Lucee `encodeFor` support note to writeOutput

- data/en/systemoutput.json
Provided a few examples of how you can use the `systemOutput()` function to write different object types to the output stream.  I also clarified the description to use the word "object" instead of "string" for clarification.
> Provided examples and clarification

- data/en/cfloop.json
Swap the from and to descriptions on the cfloop page. The examples and description of index are correct, but the from and to descriptions were reversed.
> Loop from is the beginning, to is the ending

- guides/en/operators.md
Add `DOES NOT CONTAIN` operator
Add `CT` and `NCT` Lucee shorthand 
As mentioned in https://github.com/foundeo/cfdocs/pull/1289
> Expand 'contains' operators section

- data/en/arraylast.json
Switched to make it obvious that the returned value is the actual last element, not the index of the last element.
> Updated arrayLast.json

- data/en/timeformat.json
``` 
Time zone in hourse of offset in ISO 8601 format
```
to
``` 
Time zone in hours of offset in ISO 8601 format 
```
> removed e at the end of hours

- data/en/nullvalue.json
Current example doesn't use the method it's supposed to be demonstrating.
> Fix bad example for Lucee's nullValue() function

- data/en/cfexecute.json
I'm not sure about the listed version numbers, but it looks like there's some confusion.
The ACF docs history section only references a change made in ACF6.1 (adding the `variable` attribute), with no mention of initial addition of the method.
Likewise, the Lucee docs don't mention when the method was added.
For that reason, I've removed the version numbers referenced here. Hopefully the feature is old enough that it doesn't matter any more. :)
> Fix terminateOnTimeout docs for cfexecute

- guides/en/elvis.md
Updated to warn other what I just discovered, and that is that if the value being tested is false, then the value on the right is used. This resulted in a true / false variable with a default of true always being true.
> not just null

- data/en/security-functions.json
There may be other functions missing from this list, but these were the ones I was looking for that were missing. I believe I got all of the `encodeForXYZ` functions, which was my intent.
> Add missing encodeFor functions to security list

- data/en/queryaddcolumn.json
ColumnType `timestamp` is supported in every cfml application server.  Adobe incorrectly states in their [documentation](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-m-r/queryaddcolumn.html) that "Date (can include time information)", but it doesn't and hasn't since CF11. (Specifying `date` ignores all time values.)
> ColumnType "timestamp" was missing

- data/en/esapiencode.json
and also removed parens after some named functions, so that the feature here to auto-link to them would work
> updated to point to more than just encodeforhtml

- data/en/queryreduce.json
Initial syntax and `query` callback parameters refer to "struct" instead of "query".
> Fix references to struct with query

- data/en/directorylist.json
Typo: Sort should use "desc" instead of "dec".
> Typo: Sort should use "desc" instead of "dec".

- data/en/queryaddcolumn.json
Existing example shows `addRow` instead of `addColumn` and misses an array argument.
> Fix member syntax example

- data/en/queryclear.json
I don't know if this is a bug in this project (is the JSON schema intended to always have a `params`?), or in KamasamaK's plugin; but the absence of a `params` field is unexpected in the KamasamaK plugin, and is met with an exception on a failing read in `CfDocsDefinitionInfo::toGlobalFunction`
so this could be fixed here, but might not be correct if it doesn't matter to CfDocs that there is no `params` field.
> Update queryclear.json (missing params?)

- data/en/querykeyexists.json
Lucee has supported `queryKeyExists()` since 5.1.
https://luceeserver.atlassian.net/browse/LDEV-847
> Note queryKeyExists() support on Lucee

- data/en/cfimport.json
Addresses issue #541 
* Included a basic example of using `cfimport` to include a custom tag.
* Added `cfmodule` as a "related" tag.
> cfimport example

- data/en/filesystem-functions.json
The function detail page indicated it was a filesystem function, but it wasn't listed with the other functions on the filesystem functions page.
> Added "expandPath"

- data/en/componentinfo.json
- data/en/getmetadata.json
- data/en/imagegetexifmetadata.json
- data/en/imagegetexiftag.json
- data/en/imagegetiptcmetadata.json
- data/en/onmissingmethod.json
- data/en/structsetmetadata.json
- data/en/writebody.json
I added more information to the writeBody function.  I found that the return value is boolean in that the function returns "YES" if successful.  I don't know of a way to have it return "NO", however.  If the return is not "YES", then the only other result is an error.  So, technically, it returns a boolean, but in this instance, the return value is practically useless.
I also normalized the use of "Metadata" and "EXIF" within function names.
> Improve writeBody function and normalize case of other functions

- data/en/cftransaction.json
The cftransaction page has a side note in its description that does not complete the sentence. To resolve this issue, I researched where this side note could have surfaced. It was found in the _CFMX7 manual_ according to user Newsgroup_User in the Adobe Support Community responding to this very topic. I finished the sentence as part of the reference.
Adobe Support Community Answer - [https://community.adobe.com/t5/coldfusion-discussions/cftransaction-amp-multiple-data-sources/m-p/844868](https://community.adobe.com/t5/coldfusion-discussions/cftransaction-amp-multiple-data-sources/m-p/844868)
> Newsgroup_User
> _LEGEND , May 25, 2006_
> This has been copied and pasted straight from the CFMX7 manual -
> "Within a transaction block, you can write queries to more than one
> database, but you …
> Issue #1447 - Finished side note in cftransaction description

- data/en/cacheput.json
Changed the `type` for the param `value` of `cachePut` from `string` to `any`.
Also removed the unnecessary `cfscript` tags.
> Fix cachePut value type

- assets/script.js
- doc.cfm
This was missing due to guides not having examples so the code didn't know to load the libraries, plus since the code examples were in markdown, the code blocks were missing the `.prettyprint` class. 
This was easily fixed just by applying the class before running the pretty print function and adding `request.hasExamples = true` for the guides pages
> enable prettify to highlight syntax on guides

- trycf.cfm
The CF2018 engine (acf2018) hasn't been working on TryCF.com for a couple months now. I've reached out via contact form & social media, but haven't received any response and it continues to return the following error when outputting something as simple as `writeoutput(now());`:
```
There was an error parsing your code. This usually indicates a missing ; or another compile time syntax error. Check your syntax and try again.
```
> TryCF's "CF2018" engine appears to be offline

- data/en/createdatetime.json
CF2021 & Lucee support `milliseconds`. Only Lucee supports `timezone`.
> Milliseconds & timezone update

- data/en/queryprepend.json
Member usage was wrong and raised method not found error in both 2018 and 2021. Plain .prepend works fine.
> Fix member function syntax

- data/en/queryappend.json
Member usage was wrong and raised method not found error in both 2018 and 2021. Plain .append works fine and is blessedly consistent with other data type specific append methods.
> fix member syntax

- assets/style.css
I changed the "Fork me on GitHub"-Banner because it created a horizontal scrollbar. #1495 
Now it fit better at the top right corner and does not create a scrollbar. Also the foundeo-logo is now a bit more visible.
Before/currently:
Before (when scrolling to right, because of overflow)
After:
> Fix horizontal scrollbar due "Fork me on GitHub" Banner 

- data/en/cfimage.json
The captcha sample code for cfimage was missing the required "width" and "height" attributes.
> Fix cfimage captcha example.

- data/en/entityloadbypk.json
This PR drops the `unique` attribute from the `EntityLoadByPK()` docs, since it hasn't existed in the Lucee source code since 2015.
Maybe this was 4.5 only? Or did it ever exist at all?
https://github.com/lucee/Lucee/blob/6.0/core/src/main/java/lucee/runtime/functions/orm/EntityLoadByPK.java#L11
> EntityLoadByPK() does not have a `unique` parameter in Lucee

- data/en/cflock.json
Lucee has a result attribute for returning the statusCode and ExcecutionTime of the lock as a variable.
> Added "result" attribute to cflock for Lucee

- data/en/writeoutput.json
Noticed the return type for writeOutput was incorrect.  The Adobe docs don't even mention it but the Lucee docs are correct: https://docs.lucee.org/reference/functions/writeoutput.html
> Fix return type of writeOutput

- data/en/cfzip.json
cfzipparam referenced cfzip, but cfzip didn't reference cfzipparam
> Related: Add cfzipparam

- data/en/configimport.json
Adding docs for configImport see: 
Hopefully, this will help as part of #hacktoberfest (see #1665)
> #1665 adding a configImport example

- data/en/cfswitch.json
This PR simply adds `switch (expression) { }` as the script syntax hint for [cfswitch](https://cfdocs.org/cfswitch). I figured specifying how `case`es are defined would probably be more cumbersome than practical — for that, looking at the already existing example should do.
> Add script syntax hint for cfswitch

- data/en/ormcloseallsessions.json
See ACF docs: https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-m-r/ormcloseallsessions.html
and Lucee docs: https://docs.lucee.org/reference/functions/ormcloseallsessions.html
It is clear this BIF does not take arguments.
> Drop param from ormcloseallsessions.json, there is no param in ACF or Lucee

- data/en/querysome.json
- data/en/structsome.json
The code examples in the documentation for 
querysome (https://cfdocs.org/querysome) and 
structsome (https://cfdocs.org/structsome) utilise var scoping that causes execution failures in the default Adobe ColdFusion engine when the "Run Code" button is clicked.  My solution ensures compatibility with both CFML and Lucee.
Issue:
> var scope errors on Adobe ColdFusion in examples for querysome & structsome

- assets/script.js
- views/index.cfm
- views/layout.cfm
> [!CAUTION]
> I was not able to get cfdocs running locally, so I have not been able to test these changes. However, they are small and I believe they should work. I did experiment with browser devtools to verify approaches.
The CFDocs site is responsive, which is great. But I would imagine that the majority use-case is to use the search, and when visiting on a narrow screen the search is hidden away inside the hamburger menu.
This change would -- only on narrow screens -- hide the form that collapses into the hamburger menu, and display a copy of the search form just underneath the site masthead.
> surface search on narrow screens

- data/en/cfhttp.json
- data/en/cfhttpparam.json
- data/en/cfmail.json
- data/en/cfquery.json
- data/en/htmleditformat.json
- data/en/parameterexists.json
This PR fixes #1704 by updating ColdFusion Docs to reflect features and syntax removed in ColdFusion 2025. Key changes include:
•	Annotated alternate script syntax for http, cfmail, cfquery, and cfhttpparam as removed in CF2025
•	Updated parameterExists() and htmlEditFormat() function metadata with removed: "2025" flags
•	Clarified deprecation and replacement guidance where appropriate (e.g., queryExecute() for new Query())
These updates help future-proof documentation and guide developers away from deprecated features.
> Deprecation Cleanup: Mark Removed Features for ColdFusion 2025

- data/en/cflog.json
- data/en/writelog.json
https://dev.lucee.org/t/application-log-defaults-to-error-in-6-2/14773
> Update for Lucee 6.2 breaking change to log levels

- data/en/cfparam.json
Links to `isValid` from `cfparm`, as `cfparam` uses the same type of validation as `isValid` does (there is already a link from `isValid` to `cfparam`)
> Link to `isValid` from `cfparam`

- data/en/issimplevalue.json
As both `list` and `null` may be surprising edge cases for some.
> Add example to `isSimpleValue` for list and null
