foundeo/cfdocs

- data/en/arrayappend.json
The optional merge argument was added in CF10. 
Hope I've got the format correct. Have tested that it is valid JSON.
> Add arrayAppend optional merge argument

- data/en/cfhtmltopdf.json
Hopefully this is the correct way to go about doing this - i dont use PR's internally and have never forked or done a pr to a seperate project.
Either way thought the link i added would be useful on this page as i found it hard to find when having trouble getting cfhtmltopdf set up properly.
> added link to adobe PDF Service Manager setup/usage guide

- data/en/cfcookie.json
Added full tag syntax and examples for cookies set with cfscript, tag, scope and header
> cfcookie updates

- README.md
- data/en/application-cfc.json
This example shows a bit more complicated situation of needing to map
to a different directory location and handle differences in OS paths.
> Additional App.cfc Mapping Example

- data/en/cacheput.json
typo fixed, now same as Adobe docs
> changed "idel" to "idle"

- views/index.cfm
Thought it would be a good idea to add this permanently since already a couple of us needed it to figure out why we weren't showing up.
> Add contribution test tool link

- data/en/directorylist.json
Change returnType to listInfo as per BD, CF and Lucee docs. Highlight type as CF only.
> Update to directoryList.

- data/en/queryexecute.json
"queryParams" should be "params" and "queryOptions" should be "options"
> changed the name of the 2nd two parameters

- guides/en/member.md
Also fixed some incorrect code samples at the end
> Updated list + markdown formatting

- data/en/arrayeach.json
- data/en/arraymap.json
- data/en/arrayreduce.json
- data/en/listmap.json
- data/en/listreduce.json
- data/en/structeach.json
- data/en/structmap.json
- data/en/structreduce.json
this is some examples for some functions.
> added examples to some functions

- data/en/cacheregionremove.json
- data/en/cacheremoveall.json
- data/en/callstackget.json
- data/en/encodeforjavascript.json
- data/en/encodeforurl.json
- data/en/getsystemtotalmemory.json
- data/en/gettotalspace.json
- data/en/imagemakecolortransparent.json
- data/en/lsdatetimeformat.json
- data/en/ormindex.json
- data/en/ormsearch.json
- data/en/removecachedquery.json
- guides/en/installCF/install.md
- guides/en/installCF/prep.md
- guides/en/installCF/servers.md
New Tags and Functions. The links might not all be accurate so they will
need to be reviewed.
> Added new tag and function pages with examples

- data/en/csrfgeneratetoken.json
- data/en/csrfverifytoken.json
- data/en/security-functions.json
Added CSRFGenerateToken() and CSRFVerifyToken() functions.
> Adding missing security functions

- .gitignore
- data/en/spreadsheetnew.json
- tests/tests/TestExamples.cfc
- web.config.sample
I have also added a rewrite rule for tryCF in IIS, 
Also found a small syntax issue in a test that CF didn't like.
> Documentation for spreadsheetNew

- data/en/arraydelete.json
Hi Pete,
First go at this hope it works!
Bren
> Add optional scope parameter and examples

- data/en/urldecode.json
Saw other listXXX examples are being comitted, so moved further down the list to avoid contention ;)
> Added urlDecode() examples

- data/en/arraydelete.json
> fixes incorrect description

- data/en/arrayavg.json
- data/en/arraylen.json
- data/en/insert.json
- data/en/isarray.json
- data/en/len.json
Examples for few simple functions (arrayavg, arraylen, insert, isarray & len)
> Examples for few simple functions

- data/en/listqualify.json
- data/en/listsort.json
- data/en/listtoarray.json
Examples for few simple functions (listToArray, listSort, listQualify)
> Examples for few simple functions (listToArray, listSort, listQualify)

- data/en/replacenocase.json
Tag example was actually script. Converted.
> Corrected Tag Version of ReplaceNoCase

- data/en/cfsetting.json
Also changed the description, added script syntax and added a
compatibility note.
> Added examples for cfsetting

- data/en/cfimage.json
Added basic examples for each cfimage action and added the defaults for
the params.
> cfimage examples

- data/en/createodbcdate.json
- data/en/createodbcdatetime.json
- data/en/createodbctime.json
- data/en/day.json
- data/en/dayofweek.json
- data/en/dayofyear.json
- data/en/daysinmonth.json
- data/en/daysinyear.json
- data/en/firstdayofmonth.json
- data/en/isdate.json
I have committed few examples for 10 date/time functions
> Examples for 10 date/time functions

- data/en/cfmail.json
- data/en/cfspreadsheet.json
Added CF11 params and cleaned up some examples and param explanations.
> cfmail and cfspreadsheet

- data/en/structreduce.json
Also added a dump of the original struct in the result for reference.
> Fixing error in run code for StructReduce

- data/en/cfmail.json
Add example of script function call and spelled "recipient' correctly
> CF11+ cfscript function call

- data/en/cfparam.json
- data/en/isdefined.json
Edited isdefined.json and cfparam.json.
> Added examples for <cfparam type="regex"...> and IsDefined("form.var_name")

- data/en/fileupload.json
also swapped isDefined for structKeyExists
> fileUpload: made the example more considerate

- data/en/arraycontainsnocase.json
And member function example and comments
> arrayContainsNoCase: Added ACF engine details

- data/en/application-cfc.json
Added descriptions for the new CF2016 application settings. (Issue #299)
> Application.cfc: passArrayByReference and searchImplicitScopes

- data/en/cfqueryparam.json
- data/en/structnew.json
- Added examples and the new structType argument #308 to structNew
- Fixed cfscript example on cfqueryparam
> structNew and cfqueryparam

- data/en/application-cfc.json
> inconsistent usage of double & single quotes

- guides/en/member.md
it works - http://trycf.com/gist/24a146715b823f183039dcd5cf0c417a/acf2016
> Add ArrayReduce to list of array member functions

- data/en/queryaddcolumn.json
Data type parameter value "Data" should be "Date"
> Minor correction to QueryAddColumn

- guides/en/member.md
Add trailing space after function names so links to individual doc pages can be built automatically
> Fix auto-linking of function names

- data/en/listmap.json
I couldn't find any docs on minimum version of Lucee for this function so I just guessed 4.5
> For #356, fix lucee compat warning for ListMap

- data/en/callstackget.json
Update description language for clarity and adjust example so that it works.
> Clarify example and description

- .gitignore
- data/en/directorylist.json
- guides/en/ormsettings.md
includes a small styling update to ormsettings.md
> directoryList: updated examples and rewrote params

- data/en/spreadsheetcreatesheet.json
Hope the formatting of the example works!
> Use `spreadsheetcreatesheet` in the example

- data/en/structfindkey.json
Update so that the description matches the coldfusion documentation.
> Fix error in documentation

- data/en/csrfgeneratetoken.json
- data/en/csrfverifytoken.json
Based on discussion in Slack, added an example of using CSRF with multiple open tabs to the same form
> Addl CSRF examples

- data/en/datediff.json
https://forums.adobe.com/thread/228381
> DateDiff doesn't support the millisecond date part.

- README.md
- data/en/arrayeach.json
- data/en/arrayevery.json
- data/en/arrayfilter.json
- data/en/arraymap.json
- data/en/arrayreduce.json
- data/en/arraysome.json
- data/en/listeach.json
- data/en/listevery.json
- data/en/listfilter.json
- data/en/listmap.json
- data/en/listreduce.json
- data/en/listsome.json
- data/en/queryeach.json
- data/en/queryevery.json
- data/en/queryfilter.json
- data/en/querymap.json
- data/en/queryreduce.json
- data/en/querysome.json
- data/en/structeach.json
- data/en/structevery.json
- data/en/structfilter.json
- data/en/structmap.json
- data/en/structreduce.json
- data/en/structsome.json
Added some links to many of the higher-order-function taking functions
removed unnecessary escape slashes from json documentation for link urls
> Higher-Order-Function Links

- guides/en/operators.md
Added GT, GTE, LT, LTE and their verbose counterparts
> added comparison operators

- guides/en/new.md
New operator page under the Other dropdown.  Documents most if not all of the functions of the new operator added in CF9.
> New operator

- guides/en/testbox.md
Noticed that "toBeOfType" should actually be "toBeTypeOf".
> Correcting expectation, should be toBeTypeOf

- data/en/acos.json
- data/en/arrayfind.json
- data/en/arrayfindnocase.json
- data/en/decrementvalue.json
- data/en/incrementvalue.json
- data/en/precisionevaluate.json
- tests/tests/TestExamples.cfc
I think some non-parsing json broke the missing-examples page.
Also fixed some examples that weren't going through the test suite.
> Fixed some things things that were breaking tests

- data/en/queryreduce.json
https://github.com/foundeo/cfdocs/issues/293
> added link to ACF2016

- data/en/queryreduce.json
- data/en/replacelist.json
- data/en/replacelistnocase.json
https://github.com/foundeo/cfdocs/issues/298
I would also like to add a discouraged flag, or at least a note that says that this function is rarely what you are looking for and commonly misunderstood.  Something that explains that it is a (hard to read) shortcut for doing multiple replace statements and not something like replaceListOccurance.
If you agree (and/or have any recommendations for language) let me know and ill update this PR.
> updated replacelist arguments and syntax

- data/en/filedelete.json
> Add noticed about exception in fileDelete.json

- data/en/cfargument.json
Required attribute default = No
> Required attribute default = No

- data/en/cffile.json
the variable has a typo prefixing the filename with an "f"
> fixed a type in the cffile documentation

- data/en/booleanformat.json
> Closes #443

- data/en/listlen.json
Also add descriptions for parameters and an additional code example.
closes #446
> Add includeEmptyValues to ListLen()

- data/en/application-cfc.json
onServerStart page needs to be created though
> Adding reference to onServerStart function

- data/en/cfftp.json
Improved the script example so it doesn't throw an exception then you try it. I tested this on CF11 (update 11)
> Update on cfftp.json

- data/en/callstackget.json
> Update return type

- data/en/cfschedule.json
Correct the spelling of the word scheduled
> Spelling Correction

- data/en/cfschedule.json
Correct spelling of schedule in the starttime
> Correct spelling of scheduled in file

- data/en/spreadsheetaddrows.json
I thought this example may be important to others to show them the defaults needed just to get to the includeColumnNames ordered argument.
> Add example containing includeColumnNames

- views/doc.cfm
> Display types for params #491

- views/doc.cfm
Was appended to description if provided
> Values list header should start in newline

- views/layout.cfm
> Added link to github issues

- data/en/queryfilter.json
> Added example to queryFilter

- data/en/arrayeach.json
Refers to: https://github.com/foundeo/cfdocs/issues/522
> No param data types in syntax

- data/en/datetimeformat.json
Requested in https://github.com/foundeo/cfdocs/issues/527#issuecomment-326367310
> Lucee member function was added in v5 to dateTimeFormat

- data/cfdocs.schema.json
- data/en/cfinput.json
The JSON schema may need to be tweaked, but I think this is a good basis. The `cfinput.json` file was also modified because it was invalid JSON, but I also made some type changes to match the casing in the schema enums.
> JSON schema

- data/en/tobase64.json
Add String and Object-Binary Example for ToBase64
> Add examples for ToBase64

- views/doc.cfm
> Do not allow edit when auto-generated file

- data/en/stringlen.json
> StringLen - Add Description and Examples

- data/en/listmap.json
Still throws some error with `append()` in line 7 anyway...
> Correct spelling misstake in listMap

- data/en/directorycreate.json
Added basic example of creating a directory after checking if it exists.
> directoryCreate - added cfscript example

- data/en/queryfilter.json
- data/en/querymap.json
- data/en/queryreduce.json
- data/en/ucfirst.json
- data/en/urlencode.json
> Add description to several files

- data/en/cffile.json
- data/en/cfhttp.json
- data/en/cfloop.json
> New Lucee 5 params

- data/en/arraymid.json
- data/en/arrayreverse.json
- data/en/arraysome.json
- data/en/beat.json
Made progress on issue #540 
Will add more when I can.
> Added descriptions for arrayreverse and arraymid

- data/en/cfcomponent.json
> Add CF10+ params

- data/en/cfsearch.json
#300 (would be easier with #363)
> CF2016 Updated cfsearch

- data/en/queryeach.json
> CF2016 queryEach

- data/en/isjson.json
- data/en/isnull.json
- data/en/isstruct.json
This is for #541 
- The example for isjson could not be put on one line since json objects are usually long
- Not sure if the travis tests pasts for these examples
> Added examples for isStruct isNull and isJSON

- data/cfdocs.schema.json
Added pattern to JSON schema to validation format of engine version
> Version validation #571

- data/en/createobject.json
- data/en/getfunctiondata.json
- data/en/getmetadata.json
- data/en/gettagdata.json
> Lucee5 extended functions and tags

- views/layout.cfm
https://github.com/foundeo/cfdocs/issues/519#issuecomment-325747449
> Prepare for new "Contribute" page

- data/en/lsdatetimeformat.json
> Do not write multiple signatures in one line

- guides/en/elvis.md
Correct quotes, clarify comparison example and structure sections
> [GUIDE] Rework elvis operator

- views/markdown.cfm
> Fix #609: Make guides editable

- data/en/booleanformat.json
As it turns out, I only found one. I truncated it per #571
> Fixed versions that do not match pattern

- data/en/arrayset.json
- data/en/arraytolist.json
- data/en/arraytostruct.json
- data/en/bitand.json
- data/en/bitmaskclear.json
- data/en/bitmaskread.json
- data/en/bitmaskset.json
- data/en/bitnot.json
- data/en/bitor.json
- data/en/bitxor.json
- data/en/callstackdump.json
- data/en/callstackget.json
- data/en/parsenumber.json
[Missing related](https://cfdocs.org/reports/missing-related.cfm)
[Missing examples](https://cfdocs.org/reports/missing-examples.cfm) #541 #Hacktoberfest
> [Hacktoberfest] Add related and examples

- data/en/val.json
> Fix #612 Delete undeleted character

- data/en/extract.json
Added Description / Values / Examples
> extract - Added Description / Values / Examples

- data/en/compress.json
Added Description / Values / Examples
> compress - Added Description / Values / Examples

- data/en/componentcacheclear.json
- data/en/componentcachelist.json
- data/en/getcomponentmetadata.json
[Missing related](https://cfdocs.org/reports/missing-related.cfm)
[Missing examples](https://cfdocs.org/reports/missing-examples.cfm) #541 #Hacktoberfest
> [Hacktoberfest] Add related and examples

- data/en/cacheget.json
> Add Lucee param throwWhenNotExist

- doc.cfm
> Approved 404 message

- data/en/application-cfc.json
> Correcting spelling

- data/en/applicationstarttime.json
> Added description

- data/en/cfdiv.json
- data/en/cfgrid.json
- data/en/cfgridcolumn.json
- data/en/cfgridrow.json
- data/en/cfgridupdate.json
- data/en/cfmap.json
- data/en/cfmapitem.json
- data/en/cfmenuitem.json
As requested here: https://github.com/foundeo/cfdocs/pull/657#issuecomment-339039437
> Add discouraged to CFUI tag

- data/en/cacheclear.json
- data/en/cachedelete.json
- data/en/cachegetall.json
- data/en/cachegetallids.json
- data/en/cachegetproperties.json
- data/en/cacheput.json
- data/en/cacheremoveall.json
- data/en/cachesetproperties.json
- data/en/createguid.json
- data/en/createuuid.json
- data/en/decodefromurl.json
- data/en/encodeforcss.json
- data/en/encodefordn.json
- data/en/encodeforldap.json
- data/en/encodeforurl.json
- data/en/encodeforxpath.json
- data/en/fileclose.json
- data/en/filecopy.json
- data/en/find.json
- data/en/findnocase.json
- data/en/findoneof.json
- data/en/fix.json
- data/en/getbasetagdata.json
- data/en/getbasetaglist.json
- data/en/getclasspath.json
- data/en/getvariable.json
- data/en/listfind.json
[Missing related](https://cfdocs.org/reports/missing-related.cfm)
[Missing examples](https://cfdocs.org/reports/missing-examples.cfm) #541 #Hacktoberfest
> [Hacktoberfest] Add related and description

- data/en/cfusion_encrypt.json
This pull request adds the description to the function cfusion_encrypt.
> Add description to cfusion_encrypt

- data/en/cfusion_decrypt.json
This pull request adds the description to the function cfusion_decrypt.
> Add description to cfusion_decrypt

- data/en/cfusion_decrypt.json
- data/en/cfusion_encrypt.json
Added `discouraged` keys to both `cfusion_Decrypt` and `cfusion_Encrypt`.
@pfreitag is this what you were looking for?
> Add discouraged key to cfusion_Decrypt and cfusion_Encrypt

- data/en/getk2serverdoccount.json
- data/en/getk2serverdoccountlimit.json
- data/en/gettemplatepath.json
- data/en/nowserver.json
> Right placement of deprecation notice

- assets/style.css
- views/doc.cfm
As requested here: https://github.com/foundeo/cfdocs/pull/694#issuecomment-341736343
> Moved issue button inline style to stylesheet

- assets/script.js
> Fix docname == undefined

- data/en/cfthread.json
> In Lucee and OpenBD `name` parameter is optional

- data/en/cfloop.json
Very minor cfloop example typos
> cfloop typos

- views/doc.cfm
> [ENHANCEMENT] Make doc examples collapsible

- tests/tests/TestIndexes.cfc
Resolve #593: Only test if type matches
> [CLEANUP] Speed up type tests

- data/en/cfpop.json
Add in secure argument for issue -- #751
> #751 Add secure argument

- data/en/cfpop.json
@pfreitag : It seems that I did miss some new attributes! I have made an update on the same branch. 
Thanks!
> #751 add cf11 attributes to cfpop

- data/en/structsort.json
- Add two new parameters
- Add one new signature
- Add one example
- More descriptive names for existing examples
- Cleanup existing parameters
> Some Enhancements for sortStruct()

- data/en/cfdirectory.json
- data/en/cfspreadsheet.json
- tests/tests/TestRelated.cfc
> Check related

- data/en/fileexists.json
> fix a small typo in fileExists docs

- data/en/cfqueryparam.json
> [reapply] Add engine notes for cf_sql_int oddities

- data/en/findoneof.json
We don't know the length so we don't know all values (value should be value itself not an explanation)
> Removed messy `values` value

- data/en/queryeach.json
Use engine labels and description text
> Lucee only is no description

- data/en/esapiencode.json
* increased description readability
> Cleanup esapiEncode()

- data/en/cfcookie.json
The whole signature broke the layout
> Remove optional parameters from tag syntax

- data/en/getlocalecountry.json
- data/en/getlocalelanguage.json
- Neither Open BD nor ACF ever supported that function
- Update docs state that function was added and deprecated in that version but gives not much more information
For discussion see: #760
> Fix up wrong information

- data/en/arrayevery.json
Added one example that returns a positive result and one that returns a negative result.
> Added examples to arrayEvery() function

- data/en/refind.json
> Correct return type

- data/en/cfpdf.json
Few more actions were added in CF11 and post releases.
> Update possible values to action attribute.

- assets/code-editor.js
- trycf.cfm
> Add "Adobe ColdFusion 2018" to trycf engines and set it as default

- data/en/cfldap.json
> * (!)JSON Related Tests 
>    * (!)should relate to an existing function or tag (157 ms) 
>	    * -> Failure: encodeForCN is/are non-existing function(s)/tag(s) in cfldap
> Fix wrong relation

- data/en/dollarformat.json
Fix #925
Add Lucee link as stated by @KamasamaK in https://github.com/foundeo/cfdocs/pull/925#issuecomment-423217393
> Add links to acf and lucee

- guides/en/member.md
Adds some missing CF2016 and CF2018 member functions.
> Add more member functions to data types

- data/en/queryfilter.json
I added the bug report and description.  VS Code formatted the file on save and spaced some of the JSON out.  If that is an issue I can revert the changes, turn off autoformatter and commit again.  Thanks!
> Added note in CF engine that QueryFilter mutates the original query

- data/en/invoke.json
I found myself looking for similar examples, so I figured I should add them.
> Add more invoke examples

- data/en/imagefonts.json
Added description to function from the Lucee documentation located here - https://docs.lucee.org/reference/functions/imagefonts.html
> Added description to function for imagefonts

- data/en/esapidecode.json
Added description to function from the Lucee documentation located here - https://docs.lucee.org/reference/functions/esapidecode.html
> Added description to function for ESAPIDecode

- guides/en/closures.md
Also fixes line spacing and trailing whitespace issues flagged by VSCode markdown linter.
> Add CF2016 closure functions and one missing CF11 closure function

- data/en/listsome.json
Added descriptions to arguments from the Lucee documentation located here - https://docs.lucee.org/reference/functions/listsome.html
> Added descriptions to arguments listsome

- data/en/listfilter.json
Added a member function example to listFilter
> Added member function examples and corrected syntax

- data/en/datediff.json
> Param description for the two dates in dateDiff()

- assets/script.js
Fix #872
According to https://github.com/foundeo/cfdocs/pull/872#discussion_r201046120
> Fix search redirect issue

- tests/tests/TestNamesake.cfc
Check if there's already a doc with the same name as the guide the contributer wants to create
> Introduce new test

- data/en/numberformat.json
As discussed in https://github.com/foundeo/cfdocs/pull/992#discussion_r226917350
> Relate to dollarFormat() and lsCurrencyFormat()

- data/en/isnotmap.json
- data/en/lsdayofweek.json
- data/en/query.json
- data/en/queryevery.json
> Added some missing descriptions and other improvements

- data/en/listsome.json
> Remove param inline example

- data/en/cfupdate.json
First example for how you might use cfupdate using cfscript
> Created cfupdate example

- reports/missing-version.cfm
> Make mission version report consistent

- assets/google-prettify-monokai-theme.css
- assets/style.css
- views/layout.cfm
> Replace CDN RawGit

- data/en/arrayfilter.json
> Examples runnable result

- data/en/filegetmimetype.json
* simple string output (even though filesystem functions are disabled on trycf)
* better title
> Refactor example

- data/en/datecompare.json
> y value throws an error in ColdFusion

- guides/en/operators.md
The document should be consistent, it was not and I decided to change it.
> Make comparison consistent with the rest of the document

- data/cfdocs.schema.json
As discussed in #525, here are the proposed changes. I would still be interested in feedback from @pfreitag  regarding my latest comments in that issue.
> Initial schema changes for new member_details

- data/en/fileappend.json
- data/en/fileclose.json
- data/en/filecopy.json
- data/en/filedelete.json
- data/en/fileexists.json
- data/en/filegetmimetype.json
- data/en/fileiseof.json
- data/en/filemove.json
- data/en/fileopen.json
- data/en/fileread.json
- data/en/filereadline.json
- data/en/fileseek.json
- data/en/filesetlastmodified.json
- data/en/fileskipbytes.json
- data/en/fileupload.json
- data/en/fileuploadall.json
- data/en/filewrite.json
- data/en/filewriteline.json
- data/en/find.json
- data/en/findnocase.json
- data/en/findoneof.json
- data/en/firstdayofmonth.json
- data/en/fix.json
- data/en/formatbasen.json
> Update param names for F functions

- .gitignore
- guides/en/elvis.md
I changed the isInteger (this does not exist in cf) in the examples to isNumeric. The examples are runnable now. I also added an if/elseif/else example. Lastly, I hid the `.vscode` folder, hope that's ok. Cheers!
> Changes to Elvis Operator and one more.

- data/en/cftransaction.json
- data/en/transactioncommit.json
- data/en/transactionrollback.json
- data/en/transactionsetsavepoint.json
* Link `transactionCommit()`, `transactionRollback()`, and
`transactionSetSavepoint()` as related
* Add examples
* For Pete's (pun!) sake, give a little help message on the arguments.
> Added more docs for transaction functions

- data/en/booleanformat.json
> Change return type according to lucee docs

- data/en/cfloop.json
and note about argument behavior change
> collection with both item and index in Lucee

- data/en/cfproperty.json
Added better docs for that. :)
> cfproperty unique is a Boolean value

- data/en/ormflush.json
Not vs nor. Easy fix, sorry to bug you.
> Tiny (tiny) typo in ormFlush() docs

- guides/en/security.md
Added the link for the CF2018 Lockdown Guide.
> Add CF2018 Lockdown Guide to security.md

- data/en/cfexecute.json
Document the terminateOnTimeout=false|true attribute. Also give another
example of how to use `cfexecute()`.
>  Add terminateOnTimeout attr for cfexecute

- data/en/fileappend.json
Added new parameter `addNewLine`, added docs link, and updated engine description based on ColdFusion 2016 Update 11 and ColdFusion 2018 Update 4.
> Update fileAppend for new ColdFusion updates

- data/en/render.json
@tomchiverton trying to submit your fixed pr again
> fixed json in PR #11228

- data/en/queryeach.json
- data/en/queryfilter.json
- data/en/querymap.json
- data/en/queryreduce.json
- data/en/querysort.json
Updated some descriptions and replaced links to Adam Cameron's blog with a more relevant post.
> Update descriptions and links

- views/doc.cfm
> Fix message when only one engine supports function/tag

- data/en/arrayeach.json
- data/en/arrayfilter.json
- data/en/arraymap.json
- data/en/arrayreduce.json
- data/en/arraysome.json
- data/en/queryeach.json
- data/en/queryfilter.json
- data/en/querymap.json
- data/en/queryreduce.json
- data/en/querysome.json
- data/en/structeach.json
- data/en/structfilter.json
- data/en/structmap.json
- data/en/structreduce.json
- data/en/structsome.json
>  change param "function" to "callback" for ACF compatibility

- data/en/cfheader.json
https://twitter.com/gamesover/status/1144602644788285440
> Add cfscript example of cfheader()

- data/en/ljustify.json
Improve the example so you visually see the padding whitespace
> Update lJustify example

- data/en/rjustify.json
Update example to show whitespace padding
> Update rJustify example

- guides/en/application.md
- add syntax highlighting to code samples
- fix a few typos
- reword a few sentences
> Update application.cfc docs

- data/en/cfdirectory.json
The cfdirectory filter information was incorrect/incomplete, so have updated it to be correct.
> Updating cfdirectory filter with correct information

- data/en/listfindnocase.json
Add member function details and example to listFindNoCase
> listfindnocase updates

- data/en/getbasetagdata.json
Cleaned up the example, added parameter docs, link to ACF docs page, etc.
> Add better docs to getBaseTagData()

- data/en/listfind.json
- data/en/listfindnocase.json
Add member function details to listFind. Improve formatting and member function example description in listFindNoCase
> listFind updates

- data/en/cfcomponent.json
This was added way back in 2017, so I thought we should document it. :)
> Added CF2016's invokeImplicitAccessor setting

- tests/tests/TestRelated.cfc
Occurred in https://github.com/foundeo/cfdocs/pull/1181#discussion_r327451477
> Ignore case for self-relation test

- data/en/querysort.json
Examples for numeric string, date sorts; some ascending and some descending.
> Added more querySort and .sort() examples.  

- data/en/arraygetmetadata.json
Simple example and member function. Relates to issue  #541.
> #541 Examples for arrayGetMetadata

- data/en/imageinfo.json
it was previously crashing in ACF
> fix image url in imageInfo example to be https

- data/en/fileappend.json
> Added simple example for fileappend

- data/en/getexception.json
Added simple exception for the ACF getException method.
> Created simple exception for getexception

- data/en/getapplicationmetadata.json
Added simple example using some of the properties found in ACF and Lucee application meta data.
> #541 Examples for getapplicationmetadata

- data/en/echo.json
Simple example and complex data with note to clarify that toString is not called on parameters.
> #541 Examples for echo

- data/en/arraysome.json
Added examples for simple and member function.
> #541 Examples for arraySome

- data/en/cfquery.json
Who doesn't love a good insert statement?
> Added an INSERT example

- data/en/location.json
Added simple example - relates to Issue #541.
> #541 Created simple example for location

- data/en/structinsert.json
> #541 Created two examples for structinsert

- data/en/spreadsheetnew.json
- data/en/spreadsheetsetcellvalue.json
- data/en/spreadsheetwrite.json
Lucee's docs are also being updated to reflect this: https://luceeserver.atlassian.net/browse/LD-126
> Clarify spreadsheet functions that are not supported by Lucee

- data/en/cfcatch.json
- data/en/cftry.json
- data/en/isnumeric.json
- guides/en/operators.md
No quotes needed for scientific notation
> No quotes needed

- data/en/getsoaprequest.json
- data/en/getsoapresponse.json
Provided a working example of using these to functions, and added the `webservice` parameter to `getSOAPRequest`.
> Added an example to getSOAPRequest and getSOAPResponse

- data/en/listappend.json
- data/en/listprepend.json
#1209 
Added documentation and examples for includeEmptyFields
> CF2018 Update for listappend

- guides/en/cgi-scope.md
I added some of the server variables to the guide per issue #235. If this looks good, I can probably add some client variables as well.
> Add some server variables for the CGI scope

- CONTRIBUTING.md
Should I use implicit or explicit notation for arrays and structs?
> Coding convention: implicit/explicit

- data/en/arraygetmetadata.json
- data/en/cfchart.json
- data/en/getmetadata.json
- data/en/querynew.json
> CF2018 Language Updates

- data/en/entityloadbyexample.json
> Rename E Function Params - EntityLoadByExample()

- data/en/entitynew.json
> Rename E Function Params - EntityNew()

- data/en/entityloadbypk.json
> Rename E Function Params - EntityLoadByPK()

- data/en/entitytoquery.json
> Rename E Function Params - EntityToQuery()

- data/en/serialize.json
> Fix example, add engine notes/version

- data/en/cfhttp.json
CFHTTP: All examples crash with Lucee
https://cfdocs.org/cfhttp
> Get and formfield aren't allowed with lucee

- guides/en/operators.md
> Contains operator

- CONTRIBUTING.md
> Missing semicolon

- data/en/arrayevery.json
Set minimum_version as `2018,0,05` not sure if that's how you flag the update version
> ArrayEvery added in ColdFusion 2018 u5

- data/en/arraysome.json
ArraySome was added in ACF2018u5
> ArraySome added in ACF2018u5

- data/en/cfloop.json
Updating cfloop for array to include ITEM as well as INDEX
> Updating array to include ITEM

- data/en/cfexecute.json
As suggested in https://github.com/foundeo/cfdocs/pull/1305
> Add lucee engine note for unsupported param

- data/en/cfabort.json
**Removed unwanted/extra semicolon in script syntax of cfabort**
> Removed unwanted/extra semicolon in script syntax of cfabort

- data/en/cfcookie.json
More information available from Adobe:
- https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-c/cfcookie.html
- https://helpx.adobe.com/coldfusion/kb/coldfusion-2018-update-9.html
> Add samesite param with abbreviated Adobe description

- data/en/lsparsenumber.json
Hello,
I have add "locale" param on lsParseNumber  function
> lsParseNumber add "locale" param

- data/en/cfsilent.json
Added example for cfsilent tag
> Added example for cfsilent tag

- data/en/cfclientsettings.json
Added link for Cfclientsettings tag
> Cfclientsettings links

- data/en/directorycopy.json
- data/en/empty.json
- data/en/lsisnumeric.json
Hi Foundeo,
I've added the examples about directoryCopy, Empty, Lsisnumeric. Please check it and confirm. Thanks.
> Added the examples about directorycopy,empty,lsisnumeric changes.

- data/en/applicationstop.json
Added useful links for applicationStop function.
> Added links for applicationStop function.

- data/en/storeaddacl.json
Lcase link so that it doesn't 404.
> Update broken link

- data/en/queryexecute.json
> Fix name of queryExecute options attribute per #1345

- data/en/getbasetagdata.json
> #898 - Update getbasetagdata.json

- data/en/invoke.json
RE: #1347 - Included verbiage that "instance" can be blank for CFC in same page or component,
> Update invoke "instance" description - #1347

- data/en/tostring.json
– More descriptive title for example
– Made one example runnable and removed that property from another one
– Added warning to the latter
Thanks to @MordantWastrel via https://cfml.slack.com/archives/C06T99N9G/p1606343827458100?thread_ts=1606343827.458100&cid=C06T99N9G
> Several changes to toString() function

- data/en/datediff.json
- guides/en/scopes.md
Noted that the datepart arguments "w" means Week Day (rather than Week) in Adobe ColdFusion 2018+
> datediff: datepart argument clarification

- assets/code-editor.js
- data/en/structdelete.json
- data/en/structnew.json
- data/en/structreduce.json
Added CF2021 documentation and examples of structNew
Added member function to structDelete
Fixed documentation for structAppend
Added CF2021 to the TryCF modal
> updates to the struct member functions

- data/en/application-cfc.json
CF2018 HF11 and CF2021 HF1 fixed a bug with cfinclude resolution from inside application.cfc; the fix requires a JVM flag, which ought to be documented somewhere
https://helpx.adobe.com/coldfusion/kb/coldfusion-2018-update-11.html
> new JVM flag affecting Application.cfc behavior

- data/en/listmap.json
`externalList.append` was returning an error
> fixing list append

- data/en/querygetrow.json
> Add member syntax

- guides/en/first_class.md
Multiple syntax errors. Code appears to work with Adobe ColdFusion CF11 - CF2021, but not Lucee. (Tested using TryCF.com.)
> Fixed example CFML; Add note re:compatibility

- data/en/cfdocument.json
Also tweak a typo even in the original/tag example.
> add script example

- data/en/cachegetallids.json
Documented the lucee arguments
> Documented the lucee arguments

- data/en/randrange.json
Start and End Tag has not the same Name [cftry-cfif] on line 1
> Update randrange.json cfif tag issue

- data/en/cfwhile.json
Addresses Issue #541 
* Added two examples for using cfwhile: one with the label parameter and one without
> cfwhile tag examples

- Application.cfc
- views/layout.cfm
> Fix order of "guides" drop-down display

- guides/en/cfsqltype-cheatsheet.md
I don't know if the website frontend can handle tables yet; do you need help with that?
> Turn CFSqlType_Cheatsheet into a table

- data/en/spreadsheetgetcellformula.json
Get Excel Cell Formula example
> Fixed malformed json expression for example

- guides/en/application.md
- guides/en/cfsqltype-cheatsheet.md
- guides/en/closures.md
- guides/en/coldfusion-versions.md
- guides/en/datetime.md
- guides/en/elvis.md
- guides/en/error-handling.md
- guides/en/first_class.md
- guides/en/for.md
- guides/en/java.md
- guides/en/member.md
- guides/en/new.md
- guides/en/operators.md
- guides/en/ormsettings.md
- guides/en/scopes.md
- guides/en/script.md
- guides/en/security-authentication.md
- guides/en/security-encryption.md
- guides/en/security-obfuscation.md
- guides/en/security-session-management.md
- guides/en/security.md
- guides/en/server-scope.md
- guides/en/strings.md
- guides/en/system-properties.md
- guides/en/testbox.md
- guides/en/variables-scope.md
I went through all the guides and improved and cleaned up various things.
- Spacing and formatting
- Typos
- Dead links
- Unsecured links
- Adding/fixing information
> Improve and cleanup guides

- assets/style.css
Resolves #1496
I also made the spacing a bit more consistent as I was perusing it.
> Remove h2 uppercase

- data/en/arraypop.json
Code examples have incorrect expected return values
> 20220709 arraypop fixes

- data/en/structnew.json
updated shorthand syntax for ordered case-sensitive struct
> updated shorthand syntax

- data/en/query-functions.json
> adding valueArray() function

- README.md
> Remove link to broken site cfeclipse.org

- data/en/generatesecretkey.json
Removed CFMX_COMPAT from algorithm values.
> Fixed #1532

- data/en/cfargument.json
Added values to type argument and removed extra newline characters.
> Fixed Issue #1179

- data/en/cfchart.json
- Added html to possible values
- Changed default to html
- Added note that default for lucee is png and html is not supported
Issue: #1564
> - Added html to possible values

- data/en/structappend.json
- views/doc.cfm
Member functions can return different values.
> Added memberReturns key (structAppend)

- data/en/gethttptimestring.json
Use a datetime string in the example instead of just a date.
> Use datetime in example

- assets/script.js
To prevent XSS (even though, unlikely) and improve performance (even though, only slightly)
> Use text() instead of html()

- data/en/datecompare.json
Added the member function to datecompare.json as well as an example.
> Add member function to datecompare.json

- data/en/isvalid.json
- Added "function" as possible type-parameter
- Lowercase all type-parameters
- Sort all type-parameters
close #1628
> Added "function" as possible type-parameter #1628 

- data/en/querysetcell.json
Added member function and example to querysetcell.json
> Added member function to querysetcell.json

- assets/code-editor.js
I missed the select option!
https://github.com/foundeo/cfdocs/pull/1697
> add lucee6 to drop down trycf menu!

- data/en/reescape.json
Does minimum_version support values like "6.2" i.e. when this was introduced?
> REEscape add Lucee 
